// <auto-generated />
using System;
using MediCoreHMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCoreHMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediCoreHMS.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdmissionId");

                    b.HasIndex("BedId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("MediCoreHMS.Models.Bed", b =>
                {
                    b.Property<int>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedId"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BedId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            BedId = 1,
                            BedNumber = "G-1",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 2,
                            BedNumber = "G-2",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 3,
                            BedNumber = "G-3",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 4,
                            BedNumber = "G-4",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 5,
                            BedNumber = "G-5",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 6,
                            BedNumber = "G-6",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 7,
                            BedNumber = "G-7",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 8,
                            BedNumber = "G-8",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 9,
                            BedNumber = "G-9",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 10,
                            BedNumber = "G-10",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 11,
                            BedNumber = "G-11",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 12,
                            BedNumber = "G-12",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 13,
                            BedNumber = "G-13",
                            IsOccupied = false,
                            Ward = "General"
                        },
                        new
                        {
                            BedId = 14,
                            BedNumber = "ICU-1",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 15,
                            BedNumber = "ICU-2",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 16,
                            BedNumber = "ICU-3",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 17,
                            BedNumber = "ICU-4",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 18,
                            BedNumber = "ICU-5",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 19,
                            BedNumber = "ICU-6",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 20,
                            BedNumber = "ICU-7",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 21,
                            BedNumber = "ICU-8",
                            IsOccupied = false,
                            Ward = "ICU"
                        },
                        new
                        {
                            BedId = 22,
                            BedNumber = "M-1",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 23,
                            BedNumber = "M-2",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 24,
                            BedNumber = "M-3",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 25,
                            BedNumber = "M-4",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 26,
                            BedNumber = "M-5",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 27,
                            BedNumber = "M-6",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 28,
                            BedNumber = "M-7",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 29,
                            BedNumber = "M-8",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 30,
                            BedNumber = "M-9",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 31,
                            BedNumber = "M-10",
                            IsOccupied = false,
                            Ward = "Maternity"
                        },
                        new
                        {
                            BedId = 32,
                            BedNumber = "P-1",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 33,
                            BedNumber = "P-2",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 34,
                            BedNumber = "P-3",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 35,
                            BedNumber = "P-4",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 36,
                            BedNumber = "P-5",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 37,
                            BedNumber = "P-6",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 38,
                            BedNumber = "P-7",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        },
                        new
                        {
                            BedId = 39,
                            BedNumber = "P-8",
                            IsOccupied = false,
                            Ward = "Pediatric"
                        });
                });

            modelBuilder.Entity("MediCoreHMS.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("AssignedWard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultationSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            AssignedWard = "General",
                            ConsultationSchedule = "9AM-3PM",
                            FullName = "Dr. Ahmed Raza",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            DoctorId = 2,
                            AssignedWard = "ICU",
                            ConsultationSchedule = "8AM-2PM",
                            FullName = "Dr. Sara Khan",
                            IsAvailable = true,
                            Specialization = "Intensive Care"
                        },
                        new
                        {
                            DoctorId = 3,
                            AssignedWard = "Maternity",
                            ConsultationSchedule = "10AM-4PM",
                            FullName = "Dr. Fatima Malik",
                            IsAvailable = true,
                            Specialization = "Gynecology"
                        },
                        new
                        {
                            DoctorId = 4,
                            AssignedWard = "Pediatric",
                            ConsultationSchedule = "9AM-1PM",
                            FullName = "Dr. Usman Ali",
                            IsAvailable = false,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            DoctorId = 5,
                            AssignedWard = "General",
                            ConsultationSchedule = "2PM-8PM",
                            FullName = "Dr. Bilal Qureshi",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        });
                });

            modelBuilder.Entity("MediCoreHMS.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ArrivalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MediCoreHMS.Models.Admission", b =>
                {
                    b.HasOne("MediCoreHMS.Models.Bed", "Bed")
                        .WithMany("Admissions")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCoreHMS.Models.Doctor", "Doctor")
                        .WithMany("Admissions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCoreHMS.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediCoreHMS.Models.Bed", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("MediCoreHMS.Models.Doctor", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("MediCoreHMS.Models.Patient", b =>
                {
                    b.Navigation("Admissions");
                });
#pragma warning restore 612, 618
        }
    }
}
